/* Current countries with hotels listed on Impala */
export const COUNTRIES_LIST = [
  'Andorra',
  'Anguilla',
  'Austria',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Colombia',
  'Cyprus',
  'Czech Republic',
  'Dominican Republic',
  'Egypt',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Hungary',
  'Ireland',
  'Italy',
  'Jamaica',
  'Luxembourg',
  'Mexico',
  'Montenegro',
  'Morocco',
  'Netherlands',
  'Poland',
  'Portugal',
  'Romania',
  'Saint Martin (French part)',
  'Slovakia',
  'Spain',
  'Switzerland',
  'Tunisia',
  'United Kingdom',
  'United States of America',
];
